### ISSUE TITLE
ModuleNotFoundError: No module named 'svneverever.main'

### ISSUE THREAD

**Issue by yakton** [hartwork/svneverever#5] opened 2019-07-16 00:29 UTC
I am trying to use svneverever. When I install, it fails when I try to run svneverever with an error:
`ModuleNotFoundError: No module named 'svneverever.main'`

I've created a github repo duplicating this error. 

https://github.com/yakton/svneverever-in-a-container
The requirements to run these examples in both cases are docker and docker-compose.

Installing svneverever using pip

`docker-compose run svneverever-pip`
And then running the command `svneverever`
```
root@8910fed2c381:/# svneverever
Traceback (most recent call last):
  File "/usr/local/bin/svneverever", line 6, in <module>
    from svneverever.main import main
ModuleNotFoundError: No module named 'svneverever.main'
root@8910fed2c381:/#
```

Installing svneverever using git

`docker-compose run svneverever-git`
And then running the command `svneverever`
```
root@5c00c5fa7e50:/svneverever# svneverever
Traceback (most recent call last):  File "/root/.local/bin/svneverever", line 11, in <module>
    load_entry_point('svneverever==1.4.1', 'console_scripts', 'svneverever')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'svneverever.main'
```

Thanks in advance.

**Comment by hartwork** [comment] 2019-07-16 21:54
Ouch, thanks for the report! Should be fixed in Git and PyPI now.

With that fixed you'll run into `No module named 'pysvn'` next which is caused by https://github.com/yakton/svneverever-in-a-container/blob/2c44cef24f6caee971f4330b92f6ab8f88c80ed9/Dockerfile#L2-L4 where it needs [python3-svn](https://packages.debian.org/de/sid/python3-svn), instead. I suggest
```
RUN apt-get update \
        && \
    apt-get install --yes --no-install-recommends \
            python3-svn
```
to make sure you get updates despite a Docker cache layer for `apt-get update`.

**Closed** 2019-07-16 21:55 UTC
